sudo: required

language: java

jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk11
  - openjdk11

matrix:
  include:
    - jdk: openjdk10
      install:
        # Download dependency artifacts using JDK8 (Setting for prevent "PKIX path building failed")
        - export ORIGINAL_JAVA_HOME=$JAVA_HOME
        - jdk_switcher use openjdk8
        - ./mvnw -U install -q -DskipTests=true
        - export JAVA_HOME=$ORIGINAL_JAVA_HOME

cache:
  directories:
    - $HOME/.m2
    - $HOME/.sonar/cache

install: true

script:
  - |
    if [ "$TRAVIS_BRANCH" != "master" -o "$TRAVIS_PULL_REQUEST" == "true" ]; then
        ./mvnw -U verify jacoco:report coveralls:report
    fi
  - |
    if [ "$TRAVIS_PULL_REQUEST" == "false" -a "$TRAVIS_BRANCH" == "master" ]; then
        ./mvnw -U verify jacoco:report coveralls:report sonar:sonar -Dsonar.host.url=https://sonarqube.com -Dsonar.login=${SONAR_TOKEN}
    fi
